FROM python:3.12-slim
RUN apt-get update && apt-get install -y --no-install-recommends openjdk-21-jre-headless && rm -rf /var/lib/apt/lists/*
COPY vendor/pyspark-4.2.0.tar.gz /tmp/pyspark-4.2.0.tar.gz
RUN pip install --no-cache-dir --timeout 180 --retries 20 pyarrow pandas /tmp/pyspark-4.2.0.tar.gz && rm -f /tmp/pyspark-4.2.0.tar.gz
WORKDIR /app
COPY app/ /app/
ENV OUT_PATH=/out/results.json WAREHOUSE_DIR=/tmp/warehouse SPARK_MASTER=local[*] PYSPARK_PYTHON=python3
CMD ["python3","job.py"]
